// author: Skuratovich Aliaksandr

const conferences = [{'pk': 0,
  'name': 'Interspeech',
  'brief': 'This is a brief of Interspeech2021',
  'slug': 'Interspeech2021',
  'date_from': '1.1.2021',
  'date_to': '2.2.2021',
  'image': 'https://source.unsplash.com/random',
  'price': '100$'},
 {'pk': 1,
  'name': 'Interspeech',
  'brief': 'This is a brief of Interspeech2022',
  'slug': 'Interspeech2021',
  'date_from': '1.1.2022',
  'date_to': '2.2.2022',
  'image': 'https://source.unsplash.com/random',
  'price': '100$'},
 {'pk': 2,
  'name': 'Machine Translation Marathon',
  'brief': 'This is a brief of Machine Translation Marathon2021',
  'slug': 'Machine_Translation_Marathon2022',
  'date_from': '1.1.2021',
  'date_to': '2.2.2021',
  'image': 'https://source.unsplash.com/random',
  'price': '100$'},
 {'pk': 3,
  'name': 'Machine Translation Marathon',
  'brief': 'This is a brief of Machine Translation Marathon2022',
  'slug': 'Machine_Translation_Marathon2022',
  'date_from': '1.1.2022',
  'date_to': '2.2.2022',
  'image': 'https://source.unsplash.com/random',
  'price': '100$'}
]
